apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: app
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: app
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: harika402/backend:v1
        envFrom:
        - configMapRef:
            name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: backend
    tier: app
    project: expense
  ports:
  - name: backend-port 
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port
        
